# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yhsph\Desktop\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 580)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 320, 240))
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.displayTitle = QtWidgets.QLabel(self.widget)
        self.displayTitle.setGeometry(QtCore.QRect(0, 20, 321, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.displayTitle.setFont(font)
        self.displayTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.displayTitle.setObjectName("displayTitle")
        self.displayTime = QtWidgets.QLabel(self.widget)
        self.displayTime.setGeometry(QtCore.QRect(0, 70, 321, 151))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(130)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.displayTime.setFont(font)
        self.displayTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.displayTime.setLineWidth(0)
        self.displayTime.setAlignment(QtCore.Qt.AlignCenter)
        self.displayTime.setObjectName("displayTime")
        self.displayBackground = QtWidgets.QGraphicsView(self.widget)
        self.displayBackground.setGeometry(QtCore.QRect(0, 0, 321, 241))
        self.displayBackground.setObjectName("displayBackground")
        self.displayBackground.raise_()
        self.displayTitle.raise_()
        self.displayTime.raise_()
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 290, 131, 39))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.mpGroup = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.mpGroup.setContentsMargins(0, 0, 0, 0)
        self.mpGroup.setObjectName("mpGroup")
        self.mpLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpLabel.sizePolicy().hasHeightForWidth())
        self.mpLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(12)
        self.mpLabel.setFont(font)
        self.mpLabel.setObjectName("mpLabel")
        self.mpGroup.addWidget(self.mpLabel)
        self.mpNumber = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpNumber.sizePolicy().hasHeightForWidth())
        self.mpNumber.setSizePolicy(sizePolicy)
        self.mpNumber.setObjectName("mpNumber")
        self.mpGroup.addWidget(self.mpNumber)
        self.manualMode = QtWidgets.QCheckBox(self.centralwidget)
        self.manualMode.setGeometry(QtCore.QRect(170, 300, 171, 16))
        self.manualMode.setObjectName("manualMode")
        self.modeBox = QtWidgets.QGroupBox(self.centralwidget)
        self.modeBox.setGeometry(QtCore.QRect(30, 340, 111, 131))
        self.modeBox.setObjectName("modeBox")
        self.rad_mode_pick = QtWidgets.QRadioButton(self.modeBox)
        self.rad_mode_pick.setGeometry(QtCore.QRect(10, 40, 90, 16))
        self.rad_mode_pick.setObjectName("rad_mode_pick")
        self.rad_mode_ban = QtWidgets.QRadioButton(self.modeBox)
        self.rad_mode_ban.setGeometry(QtCore.QRect(10, 60, 90, 16))
        self.rad_mode_ban.setObjectName("rad_mode_ban")
        self.rad_mode_roaster = QtWidgets.QRadioButton(self.modeBox)
        self.rad_mode_roaster.setGeometry(QtCore.QRect(10, 80, 90, 16))
        self.rad_mode_roaster.setObjectName("rad_mode_roaster")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.modeBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 91, 22))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.customModeGroup = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.customModeGroup.setContentsMargins(0, 0, 0, 0)
        self.customModeGroup.setObjectName("customModeGroup")
        self.rad_mode_custom = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.rad_mode_custom.setText("")
        self.rad_mode_custom.setObjectName("rad_mode_custom")
        self.customModeGroup.addWidget(self.rad_mode_custom)
        self.customMode = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.customMode.setObjectName("customMode")
        self.customModeGroup.addWidget(self.customMode)
        self.rad_mod_idle = QtWidgets.QRadioButton(self.modeBox)
        self.rad_mod_idle.setGeometry(QtCore.QRect(10, 20, 90, 16))
        self.rad_mod_idle.setObjectName("rad_mod_idle")
        self.teamBox = QtWidgets.QGroupBox(self.centralwidget)
        self.teamBox.setGeometry(QtCore.QRect(150, 340, 91, 131))
        self.teamBox.setObjectName("teamBox")
        self.rad_team_red = QtWidgets.QRadioButton(self.teamBox)
        self.rad_team_red.setGeometry(QtCore.QRect(10, 20, 90, 16))
        self.rad_team_red.setObjectName("rad_team_red")
        self.rad_team_blue = QtWidgets.QRadioButton(self.teamBox)
        self.rad_team_blue.setGeometry(QtCore.QRect(10, 60, 90, 16))
        self.rad_team_blue.setObjectName("rad_team_blue")
        self.rad_team_noTeam = QtWidgets.QRadioButton(self.teamBox)
        self.rad_team_noTeam.setGeometry(QtCore.QRect(10, 100, 90, 16))
        self.rad_team_noTeam.setObjectName("rad_team_noTeam")
        self.timeBox = QtWidgets.QGroupBox(self.centralwidget)
        self.timeBox.setGeometry(QtCore.QRect(250, 340, 81, 131))
        self.timeBox.setObjectName("timeBox")
        self.timeSpinner = QtWidgets.QSpinBox(self.timeBox)
        self.timeSpinner.setGeometry(QtCore.QRect(10, 50, 61, 41))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(18)
        self.timeSpinner.setFont(font)
        self.timeSpinner.setMaximum(999)
        self.timeSpinner.setObjectName("timeSpinner")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 480, 301, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.afterTimerGroup = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.afterTimerGroup.setContentsMargins(0, 0, 0, 0)
        self.afterTimerGroup.setObjectName("afterTimerGroup")
        self.afterTimerLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.afterTimerLabel.setObjectName("afterTimerLabel")
        self.afterTimerGroup.addWidget(self.afterTimerLabel)
        self.afterTimerMessage = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.afterTimerMessage.setObjectName("afterTimerMessage")
        self.afterTimerGroup.addWidget(self.afterTimerMessage)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(90, 530, 241, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.controlBox = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.controlBox.setContentsMargins(0, 0, 0, 0)
        self.controlBox.setObjectName("controlBox")
        self.resetButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.resetButton.setObjectName("resetButton")
        self.controlBox.addWidget(self.resetButton)
        self.abortButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.abortButton.setObjectName("abortButton")
        self.controlBox.addWidget(self.abortButton)
        self.setButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.setButton.setObjectName("setButton")
        self.controlBox.addWidget(self.setButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.displayTitle.setText(_translate("MainWindow", "로스터"))
        self.displayTime.setText(_translate("MainWindow", "72"))
        self.mpLabel.setText(_translate("MainWindow", "#mp_"))
        self.manualMode.setText(_translate("MainWindow", "Manual mode/Ignore IRC"))
        self.modeBox.setTitle(_translate("MainWindow", "Mode"))
        self.rad_mode_pick.setText(_translate("MainWindow", "Pick"))
        self.rad_mode_ban.setText(_translate("MainWindow", "Ban"))
        self.rad_mode_roaster.setText(_translate("MainWindow", "Roaster"))
        self.rad_mod_idle.setText(_translate("MainWindow", "Idle"))
        self.teamBox.setTitle(_translate("MainWindow", "Team"))
        self.rad_team_red.setText(_translate("MainWindow", "Red"))
        self.rad_team_blue.setText(_translate("MainWindow", "Blue"))
        self.rad_team_noTeam.setText(_translate("MainWindow", "NoTeam"))
        self.timeBox.setTitle(_translate("MainWindow", "Time"))
        self.afterTimerLabel.setText(_translate("MainWindow", "After timer :"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.abortButton.setText(_translate("MainWindow", "Abort"))
        self.setButton.setText(_translate("MainWindow", "Set!"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
